environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 9
    - nodejs_version: 10

install:
  - ps: Install-Product node $env:nodejs_version

build: off

test_script:
  - node --version
  - npm --version
  - npm test
